[2022-11-01 18:17:21,996] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2022-11-01 18:17:22,020] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2022-11-01 18:17:22,020] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-01 18:17:22,020] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-01 18:17:22,020] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-01 18:17:23,303] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-31 00:00:00+00:00
[2022-11-01 18:17:23,322] {standard_task_runner.py:52} INFO - Started process 6560 to run task
[2022-11-01 18:17:23,343] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-31T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpqbp0yjpx', '--error-file', '/tmp/tmpw9_fynvi']
[2022-11-01 18:17:23,345] {standard_task_runner.py:80} INFO - Job 15: Subtask cria_pasta
[2022-11-01 18:17:23,930] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [running]> on host nayara-S14SL01
[2022-11-01 18:17:25,195] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-31T00:00:00+00:00
[2022-11-01 18:17:25,198] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-01 18:17:25,199] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-11-01"']
[2022-11-01 18:17:25,367] {subprocess.py:85} INFO - Output:
[2022-11-01 18:17:26,423] {subprocess.py:92} INFO - mkdir: não foi possível criar o diretório “/home/millenagena”: Permissão negada
[2022-11-01 18:17:26,425] {subprocess.py:96} INFO - Command exited with return code 1
[2022-11-01 18:17:26,484] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nayara/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-11-01 18:17:26,495] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221031T000000, start_date=20221101T211721, end_date=20221101T211726
[2022-11-01 18:17:26,837] {standard_task_runner.py:92} ERROR - Failed to execute job 15 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 6560)
[2022-11-01 18:17:26,892] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-01 18:17:27,587] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
